### PR TITLE
fix(cli): fix create-t3-app to use yarn default behavior (#678)

### LINKED ISSUE #678: bug: `yarn@1` cannot run `yarn create t3-app`
### Provide environment information

System:                                                                                                                   
OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)                                                                         
CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600KF                                                                     
Memory: 12.86 GB / 15.53 GB                                                                                            
Container: Yes                                                                                                          
Shell: 5.0.17 - /bin/bash                                                                                            

Binaries:                                                                                                                 
Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node                                                                  
Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.0/bin/yarn                                                                  
npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm

### Describe the bug

When a user attempts to run `yarn create t3-app` with yarn@1, the project setup script fails. The user can still run `yarn install` afterwards to install dependencies, but I would expect the dependencies to successfully install.

### To reproduce

**Steps**

- Ensure you have yarn v. 1.x.x installed
- Run `yarn create t3-app` and follow the CLI prompts
- When you get to the output `Installing Dependencies...` you will encounter the error

### Additional information

image

### PR DESCRIPTION
**Pull request by PossibleNPC**
updated variable naming for consistency; moved changes from #681 to this one due to issues with my local repo desyncing

Closes #678 

## ✅ Checklist

- [X] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [X] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] I performed a functional test on my final commit

---

## Changelog

--- Fixed yarn to use default behavior when invoking `yarn`, which is to install dependencies
--- Updated the output of the CLI to reflect the differences in the package manager commands of yarn and not-yarn to better inform the user

## Screenshots

**pnpm install**
image

**yarn start with user wanting to run yarn**
image

**yarn start with user not wanting to run yarn through cli**
image

💯

### CODE REVIEW

File: cli/src/helpers/installDependencies.ts [hunk 1]
```diff
@@ -11,9 +11,17 @@ type Options = {
 export const installDependencies = async ({ projectDir }: Options) => {
   logger.info("Installing dependencies...");
   const pkgManager = getUserPkgManager();
-  const spinner = ora(`Running ${pkgManager} install...\n`).start();
+  const spinner =
+    pkgManager === "yarn"
+      ? ora(`Running ${pkgManager}\n`).start()
```
Comment (juliusmarminge) [inline cli/src/helpers/installDependencies.ts:16]:
```suggestion
      ? ora("Running yarn...\n").start()
```

**Review by juliusmarminge — APPROVED** [review]

**Comment by nexxeln** [comment]
Congrats @PossibleNPC! You're the 100th contributor!

**Comment by PossibleNPC** [comment]
Thanks! I'm really excited since this is also my first time contributing to OSS.

**Comment by nexxeln** [comment]
> Thanks! I'm really excited since this is also my first time contributing to OSS.

That's so cooooool
