### PR TITLE
fix: non planetscale env.js refers to YOUR_MYSQL_URL_HERE

### LINKED ISSUE #1795: bug: `.env.js` always validates `DATABASE_URL` for `YOUR_MYSQL_URL_HERE` even when using a different database provider
### Provide environment information

System:
OS: Windows 10 10.0.19045
CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
Memory: 18.68 GB / 31.94 GB
Binaries:
Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
pnpm: 8.14.1 - ~\AppData\Local\pnpm\pnpm.EXE

### Describe the bug

`.env.js` always validates `DATABASE_URL` for `YOUR_MYSQL_URL_HERE` even when using a different database.

`YOUR_MYSQL_URL_HERE` is used as a default value in `.env` and `.env.example` when choosing the planetscale option.

### Reproduction repo

N/A

### To reproduce

1. Initialize new t3 app
2. Choose any database ORM
3. Choose database provider
4. default `DATABASE_URL` in `.env` & `.env.example` does not match what `.env.js` validates

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by c-ehrlich**
Closes #1795 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

💯

### CODE REVIEW

File: cli/src/installers/envVars.ts [hunk 1]
```diff
@@ -25,9 +26,15 @@ export const envVariablesInstaller: Installer = ({
...
-  else if (usingDb) envFile = "with-db.js";
+  if (usingDb) {
+    if (usingPlanetScale) {
+      if (usingAuth) envFile = "with-auth-db-planetscale.js";
+      else envFile = "with-db-planetscale.js";
+    } else {
+      if (usingAuth) envFile = "with-auth-db.js";
+      else envFile = "with-db.js";
+    }
+  }
```
Comment (c-ehrlich) [inline cli/src/installers/envVars.ts:37]: dont love this, feel free to suggest something easier to read

File: cli/template/extras/src/env/with-auth-db-planetscale.js [hunk 2]
```diff
@@ -0,0 +1,60 @@
+import { createEnv } from "@t3-oss/env-nextjs";
+import { z } from "zod";
+
+export const env = createEnv({
+  /**
+   * Specify your server-side environment variables schema here. This way you can ensure the app
+   * isn't built with invalid env vars.
+   */
+  server: {
+    DATABASE_URL: z.string().url(),
```
Comment (juliusmarminge) [inline cli/template/extras/src/env/with-auth-db-planetscale.js:10]: what's your thought on swapping out the url for host, username and password? I tend to prefer that as it's easier to switch between different users but idk if it's just me

Comment (juliusmarminge) [inline cli/template/extras/src/env/with-auth-db-planetscale.js:10]: this looks like a planetscale file, shouldn't that have the same schema as the `with-db-planetscale`, i.e. the check for default URL?

Comment (c-ehrlich) [reply cli/template/extras/src/env/with-auth-db-planetscale.js:10]: yea

Comment (c-ehrlich) [reply cli/template/extras/src/env/with-auth-db-planetscale.js:10]: just for planetscale or also for other DBs where this can be possible (i think everything except sqlite?)

Comment (c-ehrlich) [reply cli/template/extras/src/env/with-auth-db-planetscale.js:10]: personally if im swapping locally i usually just keep two connection strings in my env file and comment one out. i don't think i would find it more convenient, but not less convenient either. maybe worse for DB providers that only give connection strings so users would have to extract host/user/pw?

dont feel strongly either way, feel free to make the change if you think it's better :)

Comment (juliusmarminge) [reply cli/template/extras/src/env/with-auth-db-planetscale.js]: Mainly planetscale maybe? Their docs suggests it: image image

No need for the ssl query param note then too

**Review by juliusmarminge — APPROVED** [review]
