### PR TITLE
fix: handle pkg with version in noInstall mode

### LINKED ISSUE #219: Getting a "EINVALIDPACKAGENAME" on fresh install
**Describe the bug**
After a fresh t3 install using the latest version, `npm install` fails because of invalid package name "react-query@3.39.2".

**To Reproduce**

1. Run `npx create-t3-app@latest`
2. Answer no to run npm install 
3. Then manually run it

**Expected behavior**
Dependencies should be installed with no failure

**Screenshots**
image

### PR DESCRIPTION
**Pull request by amyisdev**
# Handle adding package with hardcoded version in noInstall mode

- [x] I reviewed linter warnings + errors, resolved formatting, types and other issues related to my work
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

Fix #219 by extracting the package name using regex before putting the pkg string into dependency object.

### CODE REVIEW

File: src/utils/runPkgManagerInstall.ts [hunk 1]
```diff
@@ -34,11 +34,13 @@ export const runPkgManagerInstall = async (
         continue;
       }
 
+      const pkgName = pkg.replace(/^(@?[^@]+)(?:@.+)?$/, "$1");
```
Comment (juliusmarminge) [inline src/utils/runPkgManagerInstall.ts:37]: Not good with regex, would this support scoped packages too?

For example if we need to lock tRPC to a version like `@trpc/react@9.26.2`?

Comment (amyisdev) [reply src/utils/runPkgManagerInstall.ts:37]: yup, it works with scoped package.

here is some examples
image

**Comment by juliusmarminge** [comment]
Thank you for the swift support. Will publish 5.1.2 when I get home!
