### PR TITLE
fix: closes #1943

### LINKED ISSUE #1943: bug: Query data cannot be undefined error on index page
### Provide environment information

System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1
    Memory: 455.50 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    bun: 1.1.15 - ~/.bun/bin/bun
    
   ct3aMetdata.initVersion - 7.36.1

### Describe the bug

When you create new project with options like below and you log in using discord, an error will appear. 
In browser:
**Unhandled Runtime Error.** `Error: [["post","getLatest"],{"type":"query"}] data is undefined`
In console:
```
Query data cannot be undefined. Please make sure to return a value other than undefined from your query function. Affected query key: [["post","getLatest"],{"type":"query"}]
 ⨯ Internal error: Error: [["post","getLatest"],{"type":"query"}] data is undefined
    at Object.onSuccess (./node_modules/@tanstack/query-core/build/modern/query.js:241:19)
    at resolve (./node_modules/@tanstack/query-core/build/modern/retryer.js:58:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ```

### Reproduction repo

Newly created project

### To reproduce

1. Create project using `bun create t3-app@latest`. Select next-auth, drizzle, tailwind, trpc, next.js app router and sqlite as database.
2. Run `bun run db:push`
3. Start server using `bun dev`
4. Log in to your discord account
5. Observe the error: **Unhandled Runtime Error.** `Error: [["post","getLatest"],{"type":"query"}] data is undefined`

### Additional information

After replacing `const [latestPost] = api.post.getLatest.useSuspenseQuery();` in `src/app/_components/post.tsx` with `const { data: latestPost } = api.post.getLatest.useQuery();` and commenting out `void api.post.getLatest.prefetch();` in `src/app/page.tsx`, it works as expected.

Another solution is that you just manually add post using Drizzle Studio, but I don't think this is expected behaviour.

### PR DESCRIPTION
**Pull request by datasalaryman**
Closes #1943 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Handle tRPC getLatest route when there are no posts yet

---

💯

### CODE REVIEW

**Comment by datasalaryman** [comment]
First PR to an open source project this huge. Let me know if I need to do anything more or if I did something wrong. Thanks!

File: cli/template/extras/src/server/api/routers/post/with-auth-drizzle.ts [hunk 1]
```diff
@@ -29,9 +29,13 @@ export const postRouter = createTRPCRouter({
...
 
   getLatest: publicProcedure.query(({ ctx }) => {
-    return ctx.db.query.posts.findFirst({
+    const post = ctx.db.query.posts.findFirst({
       orderBy: (posts, { desc }) => [desc(posts.createdAt)],
     });
+    if (post === undefined) {
+      return null;
+    }
+    return post;
```
Comment (juliusmarminge) [inline cli/template/extras/src/server/api/routers/post/with-auth-drizzle.ts:38]: Nit: `return post ?? null`

**Review by juliusmarminge — APPROVED** [review]
