### PR TITLE
fix: tailwind is a boolean

### LINKED ISSUE #652: bug: tailwind flag has typo
### Provide environment information

n/a

### Describe the bug

The help docs for tailwind have a small typo `<tailwind>` should be `<boolean>`.

The docs have:
```ts
.option(
  "--tailwind <tailwind>",
  "Boolean value if we should install tailwind",
  (value) => value === "tailwind",
)
```

### To reproduce

```bash
npx create-t3-app --help
```

### Additional information

Happy to open a pull request to fix this 😃

### PR DESCRIPTION
**Pull request by nexxeln**
Closes #652 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Fixed tailwind flag typo in help command

---

### CODE REVIEW

File: cli/src/cli/index.ts [hunk 1]
```diff
@@ -80,7 +80,7 @@ export const runCli = async () => {
      * If any of the following option-flags are provided, we skip prompting
      */
     .option(
-      "--tailwind <tailwind>",
+      "--tailwind <boolean>",
```
Comment (juliusmarminge) [inline cli/src/cli/index.ts:83]: These are actually incorrect, the value must match the key to evaluate to true

`--tailwind=tailwind => using tailwind`
`--tailwind => nope`
`--tailwind=true => nope`

It should all be redone, it was all done in a bit of a rush and it's not very clean

**Comment by juliusmarminge** [comment]
@nexxeln Made some adjustments:

CleanShot 2022-11-03 at 14 46 32

**Comment by juliusmarminge** [comment]
CleanShot 2022-11-03 at 14 48 22@2x

**Review by juliusmarminge — APPROVED** [review]

**Comment by juliusmarminge** [comment]
> Oh cool I totally forgot about this PR lol

Same I've been super busy with other stuff but had some time over so did some clean up :)
