### PR TITLE
fix: Don't show planetscale serverless warning if not installing driver

### LINKED ISSUE #1776: bug: Warning for planetscale's driver is shown regardless of db provider
### Provide environment information

```
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 72.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.5 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.15.1 - ~/Library/pnpm/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
```

### Describe the bug

`logNextSteps` will show the warning for planetscale's driver as long as Drizzle is being used. Obviously non mySQL database providers will not get this driver installed and the warning does not need to be shown.

### Reproduction repo

limegorilla/create-t3-app

### To reproduce

Run cli, selecting drizzle as your ORM. Will produce this snippet:
image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by limegorilla**
Closes #1776

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Updates `./cli/src/helpers/logNextSteps.ts` to only show planetscale error if using the mySQL driver

---

## Screenshots

Before:
image
After:
image

If you are using mySQL you get:
image

💯

### CODE REVIEW

File: cli/src/helpers/logNextSteps.ts [hunk 1]
```diff
@@ -65,7 +65,12 @@ export const logNextSteps = async ({
 
   if (packages?.drizzle.inUse) {
     logger.warn(
-      `\nThank you for trying out the new Drizzle option. If you encounter any issues, please open an issue!`,
+      `\nThank you for trying out the new Drizzle option. If you encounter any issues, please open an issue!`
+    );
+  }
+
+  if (["mysql"].includes(databaseProvider)) {
```
Comment (juliusmarminge) [inline cli/src/helpers/logNextSteps.ts:72]:
```suggestion
  if (databaseProvider === "pscale") {
```

?

**Review by juliusmarminge — APPROVED** [review]
