### PR TITLE
fix: Reverted incorrect fixes, fixed landing page cmd

### LINKED ISSUE #1620: bug: create.t3.gg npx link is incorrect
### Provide environment information

live version of https://create.t3.gg/

### Describe the bug

throughout https://create.t3.gg/ the npx link is incorrect, it shows npx create t3-app@latest instead of npx create t3-app@latest
The - between create and t3 is missing

### Reproduction repo

https://github.com/t3-oss

### To reproduce

go to https://create.t3.gg/ and look at the main CTA and the way it is worded

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AndehUK**
Closes #1620

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Reverts all incorrect changes in #1621 and changes the displayed npx command in `banner.astro` from `npx create t3-app@latest` to `npm create t3-app@latest`

---

### Before:
image

### After:
image

💯

### CODE REVIEW

File: www/src/components/landingPage/ClipboardSelect.tsx [hunk 1]
```diff
@@ -4,19 +4,19 @@ import { Fragment, useState } from "react";
 
 const commands = [
   {
-    command: "create t3-app@latest",
+    command: "create-t3-app@latest",
```
Comment (Jacksonmills) [inline www/src/components/landingPage/ClipboardSelect.tsx:7]:
```
npm create t3-app@latest
yarn create t3-app
pnpm create t3-app@latest
bun create t3-app@latest
```

were the final commands given by @c-ehrlich 

image

**Review by Jacksonmills — CHANGES_REQUESTED** [review]
Looks good for the label fix on homepage, don't need the command changes.

File: www/src/components/landingPage/ClipboardSelect.tsx (hunk 1 above)
Comment (AndehUK) [reply www/src/components/landingPage/ClipboardSelect.tsx:7]: Sorry about that! I must have missed that when I was going over the incorrect changes from the original PR. Will get that updated now.

**Comment by AndehUK** [comment]
Accidentally left an ESLint comment in there which I have now removed, as I posted in the discord server eslint and my local config aren't agreeing with each other at the minute.

https://discord.com/channels/966627436387266600/988912020558602331/1166769760386691154

File: .changeset/spotty-students-smash.md [hunk 2]
```diff
@@ -0,0 +1,2 @@
+---
```
Comment (Jacksonmills) [inline .changeset/spotty-students-smash.md:1]: file can be deleted

Comment (AndehUK) [reply .changeset/spotty-students-smash.md:1]: Gotcha, I only added it since the `CI / Check Changeset (pull_request) ` check failed if I didn't at least have an empty .md file in there

**Review by c-ehrlich — APPROVED** [review]
thanks!
