### PR TITLE
fix: add missing `pg` dev dependency for drizzle-studio

### LINKED ISSUE #1747: bug: Drizzle needs pg
### Provide environment information

System:
    OS: macOS 14.3
    CPU: (12) arm64 Apple M2 Max
    Memory: 51.80 GB / 96.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - ~/.asdf/installs/nodejs/21.6.1/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
    bun: 1.0.25 - ~/.asdf/shims/bun

### Describe the bug

pg is not installed by default when using Drizzle and selecting postgres.

### Reproduction repo

-

### To reproduce

1. run `npm create t3-app@latest`
2. on the option "What database ORM would you like to use" select Drizzle
3. on the option "What database provider would you like to use" select PosgreSQL
4. run `npm run db:studio`
5. see error:

```
╰─ npm run db:studio                                                                                                                                                                                                                                                                                                                                                                                                           ─╯

> example-project@0.1.0 db:studio
> drizzle-kit studio

drizzle-kit: v0.20.13
drizzle-orm: v0.29.3

No config path provided, using default path
Reading config file '/example-project/drizzle.config.ts'
error please install required packages: 'pg'
```

### Additional information

it would appear t3 installs "postgres" as opposed to "pg" and because of that you get this error.  I'm super green with this tech and going through the motions trying to learn I apologize in advance if this is a waste of your time.

### PR DESCRIPTION
**Pull request by aaronmallen**
resolves #1747

Closes #<issue>

## ✅ Checklist

- [ ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [ ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I performed a functional test on my final commit

---

## Changelog

_[Short description of what has changed]_

---

## Screenshots

_[Screenshots]_

💯

### CODE REVIEW

File: cli/src/installers/drizzle.ts [hunk 1]
```diff
@@ -30,7 +30,7 @@ export const drizzleInstaller: Installer = ({
         {
           planetscale: "@planetscale/database",
           mysql: "mysql2",
-          postgres: "postgres",
```
Comment (juliusmarminge) [inline cli/src/installers/drizzle.ts:33]: We want to use the Postgres packagedor the actual querying etc. I believe pg might be a peer dependency for drizzle kit? Then we'd need to add pg as a dev dependency whilst keeping Postgres as the main production dependency

**Review by juliusmarminge — CHANGES_REQUESTED** [review]

**Review by juliusmarminge — APPROVED** [review]
