### PR TITLE
fix: add nullish coalescing operator to fix eslint error

### LINKED ISSUE #2086: bug: Build fails due to eslint/prefer-nullish-coalescing
### Provide environment information

  System:
    OS: Linux 6.11 Ubuntu 24.10 24.10 (Oracular Oriole)
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i9-13900H
    Memory: 13.04 GB / 30.50 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.7.0 - ~/.config/nvm/versions/node/v20.7.0/bin/node
    npm: 10.1.0 - ~/.config/nvm/versions/node/v20.7.0/bin/npm
    pnpm: 8.10.2 - ~ry/.local/share/pnpm/pnpm

`ct3aMetadata.initversion: 7.39.0`

### Describe the bug

The initial scaffolding, when selecting the `tRPC` and `ESLint/Prettier` options from the cli/interactive selection, will fail to compile running `pnpm build`, due to the `@typescript-eslint/prefer-nullish-coalescing` rule, at this snippet of code:

```ts 
// ./src/trpc/react.tsx
if (!clientQueryClientSingleton) {
  clientQueryClientSingleton = createQueryClient();
}
```

### Reproduction repo

https://create.t3.gg

### To reproduce

Run `pnpm create t3-app@latest`, and select both `tRPC` and `ESLint/Prettier` - any other options do not matter. Then run `pnpm build`. `next build` will fail to compile, caused by `@typescript-eslint/prefer-nullish-coalescing`

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by hengrv**
Closes #2086 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- Change IF statement to nullish coalescing operator to fix eslint error preventing build

---

## Screenshots

image

💯

### CODE REVIEW

File: cli/template/extras/src/trpc/react.tsx [hunk 1]
```diff
@@ -17,9 +17,8 @@ const getQueryClient = () => {
     return createQueryClient();
   }
   // Browser: use singleton pattern to keep the same query client
-  if (!clientQueryClientSingleton) {
-    clientQueryClientSingleton = createQueryClient();
-  }
+  clientQueryClientSingleton ??= createQueryClient();
```
Comment (juliusmarminge) [inline cli/template/extras/src/trpc/react.tsx:20]: God why are linters so opinionated 🥹🥹🥹 Biome fails on the nullish coalescence and eslint on the if statement... 🙃

Comment (hengrv) [reply cli/template/extras/src/trpc/react.tsx:20]: oh goodness 😭😭 perhaps lowering the level of the diagnostic would be a better solution?

Comment (hengrv) [reply cli/template/extras/src/trpc/react.tsx:20]: I've tested using biome on this branch, and it compiles successfully with the nullish coalescence.
image

**Review by juliusmarminge — APPROVED** [review]
